COLORS = {'tab:blue': '#1f77b4', 
          'tab:orange': '#ff7f0e', 
          'tab:green': '#2ca02c', 
          'tab:red': '#d62728',
          'tab:purple': '#9467bd', 
          'tab:brown': '#8c564b', 
          'tab:pink': '#e377c2', 
          'tab:gray': '#7f7f7f', 
          'tab:olive': '#bcbd22', 
          'tab:cyan': '#17becf',
          'xkcd:dark pastel green': '#56ae57', 
          'xkcd:dust': '#b2996e', 
          'xkcd:electric lime': '#a8ff04', 
          'xkcd:fresh green': '#69d84f', 
          'xkcd:nasty green': '#70b23f', 
          'xkcd:tea': '#65ab7c', 
          'xkcd:warm purple': '#952e8f', 
          'xkcd:yellowish tan': '#fcfc81', 
          'xkcd:cement': '#a5a391', 
          'xkcd:dark grass green': '#388004', 
          'xkcd:dusty teal': '#4c9085', 
          'xkcd:grey teal': '#5e9b8a', 
          'xkcd:macaroni and cheese': '#efb435', 
          'xkcd:pinkish tan': '#d99b82', 
          'xkcd:spruce': '#0a5f38', 
          'xkcd:strong blue': '#0c06f7', 
          'xkcd:toxic green': '#61de2a', 
          'xkcd:windows blue': '#3778bf', 
          'xkcd:blue blue': '#2242c7', 
          'xkcd:blue with a hint of purple': '#533cc6', 
          'xkcd:booger': '#9bb53c', 
          'xkcd:bright sea green': '#05ffa6',
          'xkcd:dark green blue': '#1f6357', 
          'xkcd:deep turquoise': '#017374', 
          'xkcd:green teal': '#0cb577', 
          'xkcd:strong pink': '#ff0789', 
          'xkcd:bland': '#afa88b', 
          'xkcd:deep aqua': '#08787f', 
          'xkcd:lavender pink': '#dd85d7', 
          'xkcd:olive yellow': '#c2b709', 
          'xkcd:pig pink': '#e78ea5', 
          'xkcd:deep lilac': '#966ebd', 
          'xkcd:desert': '#ccad60', 
          'xkcd:dusty lavender': '#ac86a8', 
          'xkcd:purpley grey': '#947e94', 
          'xkcd:purply': '#983fb2', 
          'xkcd:candy pink': '#ff63e9', 
          'xkcd:light pastel green': '#b2fba5', 
          'xkcd:boring green': '#63b365', 
          'xkcd:kiwi green': '#8ee53f', 
          'xkcd:orange pink': '#ff6f52', 
          'xkcd:tea green': '#bdf8a3', 
          'xkcd:very light brown': '#d3b683', 
          'xkcd:egg shell': '#fffcc4', 
          'xkcd:eggplant purple': '#430541', 
          'xkcd:powder pink': '#ffb2d0', 
          'xkcd:reddish grey': '#997570', 
          'xkcd:baby shit brown': '#ad900d', 
          'xkcd:liliac': '#c48efd', 
          'xkcd:stormy blue': '#507b9c', 
          'xkcd:ugly brown': '#7d7103', 
          'xkcd:custard': '#fffd78', 
          'xkcd:darkish pink': '#da467d', 
          'xkcd:deep brown': '#410200', 
          'xkcd:greenish beige': '#c9d179', 
          'xkcd:manilla': '#fffa86', 
          'xkcd:off blue': '#5684ae', 
          'xkcd:battleship grey': '#6b7c85', 
          'xkcd:browny green': '#6f6c0a', 
          'xkcd:bruise': '#7e4071', 
          'xkcd:kelley green': '#009337', 
          'xkcd:sickly yellow': '#d0e429', 
          'xkcd:sunny yellow': '#fff917', 
          'xkcd:azul': '#1d5dec', 
          'xkcd:darkgreen': '#054907', 
          'xkcd:green/yellow': '#b5ce08', 
          'xkcd:lichen': '#8fb67b', 
          'xkcd:pale gold': '#fdde6c', 
          'xkcd:sun yellow': '#ffdf22', 
          'xkcd:tan green': '#a9be70', 
          'xkcd:burple': '#6832e3', 
          'xkcd:butterscotch': '#fdb147', 
          'xkcd:toupe': '#c7ac7d', 
          'xkcd:dark cream': '#fff39a', 
          'xkcd:indian red': '#850e04', 
          'xkcd:light lavendar': '#efc0fe', 
          'xkcd:poison green': '#40fd14', 
          'xkcd:baby puke green': '#b6c406', 
          'xkcd:bright yellow green': '#9dff00'}